{
  "uid" : "30ec82a3254ac30b",
  "name" : "Failure login to D3O with invalid username",
  "fullName" : "D3O Login: Failure login to D3O with invalid username",
  "historyId" : "03e76f8e44f01f998bd0d2630950195e",
  "time" : {
    "start" : 1630840596047,
    "stop" : 1630840605573,
    "duration" : 9526
  },
  "status" : "broken",
  "statusMessage" : "TypeError: __call__() got an unexpected keyword argument 'type'\n",
  "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 50, in assert_login_unsuccessful\n    allure.attach('screenshot2', context.driver.get_screenshot_as_png(), type=allure.attachment_type.PNG)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: __call__() got an unexpected keyword argument 'type'\n",
    "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 50, in assert_login_unsuccessful\n    allure.attach('screenshot2', context.driver.get_screenshot_as_png(), type=allure.attachment_type.PNG)\n",
    "steps" : [ {
      "name" : "Given the user launches Chrome Browser",
      "time" : {
        "start" : 1630840596057,
        "stop" : 1630840597696,
        "duration" : 1639
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "When the user opens D3a login page url \"https://www.d3a.io/login\"",
      "time" : {
        "start" : 1630840597700,
        "stop" : 1630840600748,
        "duration" : 3048
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "When the user enters username \"wrongemail1@gmail.com\" and password \"11-Feb-1995\"",
      "time" : {
        "start" : 1630840600748,
        "stop" : 1630840601115,
        "duration" : 367
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "And the user clicks the Login Button",
      "time" : {
        "start" : 1630840601116,
        "stop" : 1630840605248,
        "duration" : 4132
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "Then the home page does not open with invalid username",
      "time" : {
        "start" : 1630840605248,
        "stop" : 1630840605572,
        "duration" : 324
      },
      "status" : "broken",
      "statusMessage" : "TypeError: __call__() got an unexpected keyword argument 'type'\n",
      "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 50, in assert_login_unsuccessful\n    allure.attach('screenshot2', context.driver.get_screenshot_as_png(), type=allure.attachment_type.PNG)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : true,
      "attachmentsCount" : 0,
      "hasContent" : true,
      "stepsCount" : 0
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : true,
    "stepsCount" : 5
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "D3O Login"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "30ec82a3254ac30b.json",
  "parameterValues" : [ ]
}